// Generated by CoffeeScript 1.4.0
(function() {
  var i, imgs, next;

  i = 0;

  imgs = ['cradle', 'branch', 'sun-grass', 'field'];

  next = function() {
    var active, img, inactive;
    i++;
    if (i === imgs.length) {
      i = 0;
    }
    img = imgs[i];
    console.log(img);
    active = document.querySelector('.bg.active');
    inactive = document.querySelector('.bg.inactive');
    inactive.setAttribute('style', "background-image: url('img/" + img + ".jpg')");
    return setTimeout(function() {
      active.setAttribute('class', 'bg inactive');
      return inactive.setAttribute('class', 'bg active');
    }, 3 * 1000);
  };

  setInterval(next, 10 * 1000);

}).call(this);
