// Generated by CoffeeScript 1.3.3
(function() {
  var i, imgs, next;

  i = 0;

  imgs = ['cradle', 'sun-cradle', 'wallaby', 'bayoffires', 'branch', 'sun-grass', 'devil', 'field', 'freycinet', 'lake', 'lizard', 'richmond', 'sun-road'];

  next = function() {
    var active, img, inactive;
    i++;
    if (i === imgs.length) {
      i = 0;
    }
    img = imgs[i];
    console.log(img);
    active = document.querySelector('.bg.active');
    inactive = document.querySelector('.bg.inactive');
    inactive.setAttribute('style', "background-image: url('img/tazzie/" + img + ".jpg')");
    return setTimeout(function() {
      active.setAttribute('class', 'bg inactive');
      inactive.setAttribute('class', 'bg active');
      return setTimeout(next, 3 * 1000);
    }, 12 * 1000);
  };

  setTimeout(next, 12 * 1000);

}).call(this);
